lash_store/orders/urls.py
from django.urls import path
from lash_store.orders.views import cart_summary, add_to_cart_ajax, delete_cart_item, update_cart_item_quantity_ajax, \
    checkout_view, order_confirmation_view, orders_history_view, order_detail_view

urlpatterns = [
    path('', checkout_view, name='checkout'),
    path('confirmation/<int:pk>/', order_confirmation_view, name='order_confirmation'),
    path ('cart/', cart_summary, name='cart_summary'),
    path('add_to_cart/<int:product_id>/', add_to_cart_ajax, name='add_to_cart'),
    path('cart/<int:pk>/delete/', delete_cart_item, name='delete_cart_item'),
    path('cart/<int:cart_item_id>/update/', update_cart_item_quantity_ajax, name='update_cart_item'),
    path('orders/', orders_history_view, name='orders_history'),
    path('orders/<int:pk>/', order_detail_view, name='order_details'),
]

lash_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from lash_store.settings import DEBUG

urlpatterns = [
    path("", include('lash_store.common.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("profile/", include("lash_store.accounts.url")),
    path("i18n/", include("django.conf.urls.i18n")),
    path('product/', include("lash_store.product.urls")),
    path('checkout/', include("lash_store.orders.urls")),
    path('contact/', include("lash_store.contact.urls")),
    path('blog/', include("lash_store.blog.urls")),
    path('cookie_consent/', include('cookie_consent.urls')),
]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lash_store/orders/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db import models
from lash_store.product.models import Product

UserModel = get_user_model()

class Order(models.Model):
    PRICE_MAX_DIGITS = 6
    PRICE_DECIMAL_PLACES = 2
    MAX_STATUS_LENGTH = 10
    STATUS_CHOICES = [
        ('Pending', 'Очаква се'),
        ('Processing', 'В обработка'),
        ('Completed', 'Завършена'),
        ('Cancelled', 'Отменена'),
    ]
    PAYMENT_STATUS_CHOICES = [
        ('unpaid', 'Неплатена'),
        ('paid', 'Платена'),
        ('refunded', 'Възстановена'),
    ]

    customer = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
        verbose_name='Клиент',
    )
    status = models.CharField(
        max_length=MAX_STATUS_LENGTH,
        choices=STATUS_CHOICES,
        default='Pending',
        verbose_name='Статус на поръчката',
    )

    total_price = models.DecimalField(
        max_digits=PRICE_MAX_DIGITS,
        decimal_places=PRICE_DECIMAL_PLACES,
        verbose_name='Обща сума',
    )

    payment_status = models.CharField(
        max_length=10,
        choices=PAYMENT_STATUS_CHOICES,
        default='unpaid',
        verbose_name='Статус на плащане',
    )

    note = models.TextField(
        blank=True,
        null=True,
        verbose_name='Бележка',
    )

    email_sent = models.BooleanField(default=False)

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата на създаване',
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Последна промяна',
    )

    def __str__(self):
        return f"Поръчка #{self.id} - статус: {self.get_status_display()}"

    @property
    def calculated_total_price(self):
        return sum(item.product.price * item.quantity for item in self.items.all())

    def clean(self):
        shipping = getattr(self, 'shippingaddress', None)
        if shipping and shipping.payment_method == 'bank_payment':
            if self.status in ['Processing', 'Completed'] and self.payment_status != 'paid':
                raise ValidationError("Поръчките с банково плащане трябва да бъдат платени преди да се обработят.")


class OrderItem(models.Model):
    PRICE_MAX_DIGITS = 6
    PRICE_DECIMAL_PLACES = 2

    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name='items'
    )

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name= 'Продукт'
    )

    quantity = models.PositiveIntegerField(
        verbose_name= 'Количество'
    )

    saved_price = models.DecimalField(
        max_digits=PRICE_MAX_DIGITS,
        decimal_places=PRICE_DECIMAL_PLACES,
        verbose_name= 'Стойност'
    )

    @property
    def price(self):
        return self.quantity * self.product.price

    def save(self, *args, **kwargs):
        # price calculation
        self.saved_price = self.price
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Поръчани {self.quantity} бр. от {self.product}"


class Cart(models.Model):
    user = models.OneToOneField(
        UserModel,
        on_delete=models.CASCADE,
        null=True, blank=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )


class CartItem(models.Model):
    cart = models.ForeignKey(
        Cart,
        on_delete=models.CASCADE,
        related_name='items',
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )

    quantity = models.PositiveIntegerField(
        default=1,
    )

    def __str__(self):
        return f"{self.quantity} x {self.product} in cart"


class ShippingAddress(models.Model):
    MAX_CITY_LENGTH = 50
    MAX_NAME_LENGTH = 35
    MAX_PHONE_NUMBER_LENGTH = 13
    MAX_POSTAL_CODE_LENGTH = 4
    MAX_PAYMENT_METHOD_LENGTH = 20
    PAYMENT_CHOICES = [
        ('pay_on_delivery', 'Плати при доставка'),
        ('bank_payment', 'Банков превод'),
    ]

    name = models.CharField(
        max_length=MAX_NAME_LENGTH,
        verbose_name= 'Име за доставката'
    )

    phone_number = models.CharField(
        max_length=MAX_PHONE_NUMBER_LENGTH,
        validators=[RegexValidator(
            regex=r"^((?:\+359|0)8[7-9]\d{7}|(?:\+359|0)[2-9]\d{6,8})$",
            message="Моля въведете валиден телефоне номер с формат 0888123456"
        )],
        verbose_name='Телефонен номер за доставката'
    )

    email = models.EmailField()

    customer = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
        verbose_name='Клиент'
    )

    order = models.OneToOneField(
        Order,
        on_delete=models.CASCADE
    )

    address = models.TextField(
        verbose_name='Адрес за доставка'
    )

    city = models.CharField(
        max_length=MAX_CITY_LENGTH,
        verbose_name='Град'
    )

    postal_code = models.CharField(
        max_length=MAX_POSTAL_CODE_LENGTH,
        verbose_name='Пощенски код'
    )

    payment_method = models.CharField(
        max_length=MAX_PAYMENT_METHOD_LENGTH,
        choices=PAYMENT_CHOICES,
        default='pay_on_delivery',
        verbose_name='Мотод на плащане'
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    def __str__(self):
        return f"Адрес за доставка за {self.order}"

lash_store/orders/views.py
import json

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMultiAlternatives
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.views import generic as views

from lash_store.orders.decorators import ajax_login_required
from lash_store.orders.forms import CheckoutForm
from lash_store.orders.models import Cart, CartItem, OrderItem, Order
from lash_store.product.models import Product


class CartSummaryView(LoginRequiredMixin,views.ListView):
    model = CartItem
    template_name = 'orders/cart.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        cart, created = Cart.objects.get_or_create(user=self.request.user)
        return cart.items.select_related('product').all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_items = context['object_list']
        context['total'] = sum(item.product.price * item.quantity for item in cart_items)
        return context

cart_summary = CartSummaryView.as_view()

@ajax_login_required
def add_to_cart_ajax(request, product_id):
    if request.method == "POST":
        product = get_object_or_404(Product, pk=product_id)
        data = json.loads(request.body)
        quantity = int(data.get("quantity"))

        cart, created = Cart.objects.get_or_create(user=request.user)
        item, created = CartItem.objects.get_or_create(cart=cart, product=product)

        item.quantity += quantity -1 if created else quantity
        message = "Продуктът е добавен в кошницата"

        if item.quantity > item.product.stock:
            item.quantity = item.product.stock
            message = f"От този продукт може да купите максимум {item.product.stock} бр."


        item.save()

        picture_url = product.images.first().image.url if product.images.exists() else ''

        return JsonResponse({
            "success": True,
            "message": message,
            "product_details": {
                "name": product.name,
                "price": str(product.price),
                "quantity": item.quantity,
                "picture": picture_url,
                "slug": product.slug,
            }
        })
    return JsonResponse({"success": False, "message": "Невалидна заявка"})


class DeleteCartItemView(LoginRequiredMixin,views.View):
    def post(self, request, pk):
        cart_item = get_object_or_404(CartItem, pk=pk, cart__user=self.request.user)

        product_name = cart_item.product.name
        cart_item.delete()
        messages.success(request, f"Продукта {product_name} е успешно премахнат от кошницата.")
        return HttpResponseRedirect(reverse('cart_summary'))

delete_cart_item = DeleteCartItemView.as_view()

@ajax_login_required
def update_cart_item_quantity_ajax(request, cart_item_id):
    if request.method == "POST":
        cart_item = get_object_or_404(CartItem, pk=cart_item_id)
        data = json.loads(request.body)
        quantity = int(data.get("quantity"))

        cart_item.quantity += quantity
        if cart_item.quantity == 0:
            cart_item.quantity=1
        message = "Количеството е обновено успешно"

        if cart_item.quantity > cart_item.product.stock:
            cart_item.quantity = cart_item.product.stock
            message = f"От този продукт може да купите максимум {cart_item.product.stock} бр."

        cart_item.save()

        return JsonResponse({
            "success": True,
            "message": message,
            "product_details": {
                "quantity": cart_item.quantity,
                "total_price": str(cart_item.product.price * cart_item.quantity),
                "cart_total": str(sum(item.product.price * item.quantity for item in cart_item.cart.items.all())),
            }
        })
    return JsonResponse({"success": False, "message": "Невалидна заявка"})


class CheckoutView(LoginRequiredMixin, views.FormView):
    template_name = 'orders/checkout.html'
    form_class = CheckoutForm
    order_id = None

    def get_success_url(self):
        return reverse_lazy('order_confirmation', kwargs={'pk': self.order_id})

    def get(self, request, *args, **kwargs):
        if not self.get_cart_items().exists():
            messages.warning(request, "Вашата количка е празна. Добавете продукти преди да завършите поръчката.")
            return redirect('cart_summary')
        return super().get(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_items = self.get_cart_items()
        context['cart_items'] = cart_items
        context['total'] = self.calculate_total_price(cart_items)
        return context

    def form_valid(self, form):
        cart_items = self.get_cart_items()

        if not cart_items.exists():
            messages.error(self.request, "Вашата количка е празна. Добавете продукти преди да завършите поръчката.")
            return redirect('cart_summary')

        order = form.save()
        self.order_id = order.id

        OrderItem.objects.bulk_create([
            OrderItem(
                order=order,
                product=cart_item.product,
                quantity=cart_item.quantity,
                saved_price=cart_item.product.price*cart_item.quantity,
            ) for cart_item in cart_items
        ])

        for item in cart_items:
            item.product.units_sold += item.quantity
            # item.product.stock -= item.quantity    # logic for stock reduction
            item.product.save()

        cart_items.delete()

        messages.success(self.request, "Поръчката е изпратена за обработка!")
        return super().form_valid(form)

    @staticmethod
    def calculate_total_price(items):
        total_price = sum(item.product.price * item.quantity for item in items)
        return total_price

    def get_cart_items(self):
        return CartItem.objects.filter(cart__user=self.request.user).select_related('product').all()

checkout_view = CheckoutView.as_view()

class OrderConfirmationView(LoginRequiredMixin, views.DetailView):
    model = Order
    template_name = 'orders/order_confirmation.html'
    context_object_name = 'order'

    def get_queryset(self):
        return Order.objects.filter(customer=self.request.user)

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        self.send_confirmation_email()
        return response

    def send_confirmation_email(self):
        order = self.get_object()

        if order.email_sent:
            return

        shipping = getattr(order, 'shippingaddress', None)
        if not shipping:
            return

        subject = f"Потвърждение за поръчка № {order.created_at.strftime('%y%m%d')}-{order.id}"
        from_email = 'no_reply@lashstore.bg'
        to_email = [shipping.email]

        html_content = render_to_string('email/order_confirmation_email.html', {
            'order': order,
        })

        email_message = EmailMultiAlternatives(
            subject=subject,
            body="Вашата поръчка е регистрирана успешно.",
            from_email=from_email,
            to=to_email,
        )
        email_message.attach_alternative(html_content, "text/html")
        email_message.send(fail_silently=False)

        order.email_sent = True
        order.save(update_fields=['email_sent'])


order_confirmation_view = OrderConfirmationView.as_view()

class OrderHistoryView(LoginRequiredMixin, views.ListView):
    model = Order
    template_name = 'orders/orders_history.html'
    context_object_name = 'orders'
    # paginate_by = 5

    def get_queryset(self):
        return Order.objects.filter(customer=self.request.user).order_by('-created_at')

orders_history_view = OrderHistoryView.as_view()

class OrderDetailView(LoginRequiredMixin, views.DetailView):
    model = Order
    template_name = 'orders/order_details.html'

    def get_queryset(self):
        return Order.objects.filter(customer=self.request.user)

order_detail_view = OrderDetailView.as_view()

templates/orders/cart.html
{% extends 'base.html' %}
{% load cart_item_summary_tag %}
{% load static %}
{% block extra_head_script %}
<link rel="stylesheet" href="{% static 'css/cart.css' %}">
{% endblock %}
{% block body %}
{%include 'partials/messages.html' %}
<div class="cart-container">
    <div class="cart-details">
        {% if object_list %}
        <div class="cart-title">
            <h2>Количка</h2>
            <a href="{% url 'products' %}"><span>Продължи пазаруването</span></a>
        </div>
        <div class="cart-list">
            <table class="table">
                <thead>
                    <tr>
                        <th>Продукт</th>
                        <th></th>
                        <th>Количество</th>
                        <th>Цена</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cart_item in object_list %}
                    <tr class="cart-item" id="item-{{ cart_item.pk }}">
                        <td class="cart-item-media">
                            <a href="{% url 'product_details' slug=cart_item.product.slug %}">
                                <img src="{{cart_item.product.images.first.image.url}}"
                                    alt="product {{ cart_item.product.name }} image">
                            </a>
                        </td>
                        <td class="cart-item-name">
                            <a href="{% url 'product_details' slug=cart_item.product.slug %}"
                                class="details-product-name">{{ cart_item.product.name }}</a>
                        </td>
                        <td class="cart-item-quantity">
                            <div class="cart-item-quantity-wrapper">
                                <div class="quantity-wrapper">
                                        <button  onclick="updateCartItem({{ cart_item.pk }}, -1)" type="submit"
                                                 name="action" value="decrease" class="qty-btn" data-action="decrease"
                                            aria-label="Намали количество">
                                            <i class="fas fa-minus fa-2xs"></i>
                                        </button>
                                        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                                        <input type="number" id="quantity-{{cart_item.pk}}" class="quantity quantity-input" name="quantity"
                                            value="{{ cart_item.quantity }}" min="1" max="{{ cart_item.product.stock }}"
                                            aria-live="polite" disabled>
                                        <button  onclick="updateCartItem({{ cart_item.pk }}, 1)" type="submit"
                                                 name="action" value="increase" class="qty-btn" data-action="increase"
                                            aria-label="Увеличи количество">
                                            <i class="fas fa-plus fa-2xs"></i>
                                        </button>
                                </div>
                                <div class="remove-button">
                                    <form method="post" action="{% url 'delete_cart_item' pk=cart_item.pk %}"
                                        class="form-delete">
                                        <button><i class="fa fa-trash"></i></button>
                                        {% csrf_token %}
                                    </form>
                                </div>
                            </div>

                            <p class="stock-message" style="color: red; margin-top: 5px; display:none;"></p>
                        </td>
                        <td class="cart-item-price">
                            <span class="price"> {{ cart_item.product.price|multiply:cart_item.quantity }} лв</span>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="summary">
            <div class="summary-row"><span>Стойност на продуктите </span><span class="total-price">{{ total }} лв</span>
            </div>
            <div class="proceed-to-checkout">
                <a href="{%  url 'checkout' %}" class="btn">Звършете поръчката</a>
            </div>
        </div>
        {% else %}
        <p>Количката е празна <a href="{% url 'products' %}">Продължи пазаруване</a></p>
        {% endif %}
    </div>
</div>
{% endblock %}
{% block extra_body %}
<script src="{% static 'js/update_cart_item.js' %}"></script>
{% endblock extra_body %}

templates/orders/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load cart_item_summary_tag %}
{% load show_field_error %}
{% block extra_head_script %}
<link rel="stylesheet" href="{% static 'css/checkout.css' %}">
{% endblock %}
{% block body %}
{%include 'partials/messages.html' %}
<div class="checkout-container">
    <h2 class="checkout-header">Завършване на поръчката</h2>
    <form action="{% url 'checkout' %}" method="post">
        {% csrf_token %}
        <div class="form-wrapper">
            <div class="col-left">
                <div class="delivery-info-body">
                    <h3 class="card-title">Данни за доставка</h3>
                    {% csrf_token %}
                    <div class="floating-group input-container">
                        {{ form.name}}
                        <label for="{{ form.name.id_for_label }}">Име и фамилия</label>
                        {% render_field_errors form.name %}
                    </div>
                    <div class="floating-group input-container">
                        {{ form.phone_number }}
                        <label for="{{ form.phone_number.id_for_label }}">Телефонен номер</label>
                        {% render_field_errors form.phone_number %}
                    </div>
                    <div class="floating-group input-container">
                        {{ form.email }}
                        <label for="{{ form.address.id_for_label }}">Имейл адрес</label>
                        {% render_field_errors form.email %}
                    </div>
                    <div class="floating-group">
                        {{ form.address }}
                        <label for="{{ form.address.id_for_label }}">Адрес за доставка</label>
                        {% render_field_errors form.address %}
                    </div>
                    <div class="floating-group input-container">
                        {{ form.city }}
                        <label for="{{ form.city.id_for_label }}">Град</label>
                        {% render_field_errors form.city %}
                    </div>
                    <div class="floating-group input-container">
                        {{ form.postal_code }}
                        <label for="{{ form.postal_code.id_for_label }}">Пощенски код</label>
                        {% render_field_errors form.postal_code %}
                    </div>
                    <div class="floating-group">
                        {{ form.note }}
                        <label for="{{ form.note.id_for_label }}">Бележка към поръчката</label>
                        {% render_field_errors form.note %}
                    </div>
                </div>
            </div>
            <!-- Order Summary -->
            <div class="col-right">
                <div class="order-info-body">
                    <h3 class="card-title">Поръчка</h3>
                    <table class="order-table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Продукти</th>
                                <th>Цена</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart_items %}
                            <tr>
                            <td class="product-image">
                                <a href="{% url 'product_details' slug=item.product.slug %}">
                                    <img src="{{ item.product.images.first.image.url }}"
                                    alt="product {{ item.product.name }} image">
                                </a>
                            </td>
                                <td>
                                    <p>{{ item.product.name }}</p>
                                    <p>Количество: {{ item.quantity }} бр.</p>
                                    <p>Единична цена: {{ item.product.price }} лв</p>
                                 </td>
                                <td class="price-centered">{{ item.product.price|multiply:item.quantity }} лв</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th></th>
                                <th>Обща сума</th>
                                <th>{{ total }} лв</th>
                            </tr>
                        </tfoot>
                    </table>
                    <div class="mb-3 m-4">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="payment_method" id="payOnDelivery"
                                value="pay_on_delivery" checked>
                            <label class="form-check-label" for="payOnDelivery">
                                Наложен платеж
                            </label>
                            <small class="form-text text-muted">Заплатете сумата директно на куриера при получаване на
                                поръчката. Не се изисква авансово плащане.</small>
                        </div>
                    </div>
                    <div class="mb-3 m-4">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="payment_method" id="bankPayment"
                                value="bank_payment">
                            <label class="form-check-label" for="bankPayment">
                                Банков превод
                            </label>
                            <small class="form-text text-muted">Преведете сумата директно по нашата банкова сметка.
                                Използвайте номера на поръчката като основание за плащането. Поръчката ще бъде
                                обработена след потвърждаване на плащането.</small>
                        </div>
                    </div>
                    <div class="action-button">
                        <button type="submit" class="btn place-order">Поръчай</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/orders/order_confirmation.html
{% extends 'base.html' %}
{% load static %}
{% load order_item_price %}
{% block extra_head_script %}
<link rel="stylesheet" href="{% static 'css/order_confirmation.css' %}">
{% endblock %}
{% block body %}
{%include 'partials/messages.html' %}
<div class="container-confirmation">
    <div class="confirmation-wrapper">
        <header>
            {% block order_header %}
            <h2 class="confirmation-header">Вашата поръчка е изпратена за обработка</h2>
            {% endblock %}
            <p>Поръчка № {{ order.created_at|date:'ymd' }}-{{ order.id }}</p>
            <p>Дата: <time datetime="{{ order.created_at|date:'Y-m-d' }}">{{ order.created_at|date:'d.m.Y' }}</time></p>
            <p>Статус на поръчката: {{ order.get_status_display }}</p>
            <p>Статус на плащането: {{ order.get_payment_status_display }}</p>
        </header>
        <article>
            <h4 class="order-confirmation-details">Детайли на поръчката</h4>
            <table class="confirmation-table">
                <thead>
                    <tr>
                        <th>Продукт</th>
                        <th>Междинна сума</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in order.items.all %}
                    <tr>
                        <td>
                            <p><strong>{{ item.product.name }}</strong></p>
                            <p>Количество: {{ item.quantity }} бр.</p>
                            <p>Цена за брой: {{ item.saved_price|divide:item.quantity }} лв</p>
                        </td>
                        <td>{{ item.saved_price }} лв</td>
                    </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="1"><strong>Обща сума:</strong></td>
                        <td><strong>{{ order.total_price }} лв</strong></td>
                    </tr>
                </tfoot>
            </table>
            <h4 class="shipping-details-title">Данни за доставка</h4>
            <address class="shipping-details">
                <p>{{ order.shippingaddress.name }}</p>
                <p>{{ order.shippingaddress.address }}</p>
                <p>{{ order.shippingaddress.city }}, {{ order.shippingaddress.postal_code }}</p>
                <p><a href="mailto:{{ order.shippingaddress.email }}">{{ order.shippingaddress.email }}</a></p>
                <p><a href="tel:{{ order.shippingaddress.phone_number }}">{{ order.shippingaddress.phone_number }}</a>
                </p>
                {% if order.note %}
                <p><em>Бележка: {{ order.note }}</em></p>
                {% endif %}
            </address>
        </article>
        <div class="action-buttons">
            <a href="{% url 'orders_history' %}" class="btn action-button">История на поръчките</a>
            <a href="{% url 'products' %}" class="btn action-button">Продължи с пазаруването</a>
        </div>
    </div>
</div>
{% endblock %}

templates/orders/order_details.html
{% extends 'orders/order_confirmation.html' %}
{% block order_header %}
{% endblock %}

templates/orders/orders_history.html
{% extends 'base.html' %}
{% load static %}
{% load order_item_price %}
{% block extra_head_script %}
<link rel="stylesheet" href="{% static 'css/orders_history.css' %}">
{% endblock %}
{% block body %}
<div class="container-orders-history">
  <div class="history-wrapper">
    <h2 class="orders-history-header">История на поръчките</h2>
    {% include 'partials/messages.html' %}
    <table class="orders-history-table">
      <thead>
        <tr>
          <th>№</th>
          <th>Дата</th>
          <th>Статус</th>
          <th>Обща сума</th>
          <th>Действия</th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
        <tr>
          <td data-label="№">{{ order.created_at|date:'ymd' }}-{{ order.id }}</td>
          <td data-label="Дата">{{ order.created_at|date:'d.m.Y' }}</td>
          <td data-label="Статус">{{ order.get_status_display }}</td>
          <td data-label="Обща сума">{{ order.total_price }} лв</td>
          <td data-label="Действия">
            <a href="{% url 'order_details' pk=order.pk%}" class="btn btn-sm">Детайли</a>
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="5">Нямате направени поръчки.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}